title: Delaney Sullivan
email: DSullivan@mednet.ucla.edu
description: >- # this means to ignore newlines until "baseurl:"
  Delaney Sullivan
twitter_username: '@DelaneySulliva2'
github_username: Yenaled
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.16.5
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Delaney Sullivan"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "<b>UCLA-Caltech</b><br>
  M.D./Ph.D. Student
  <br><br>
  <b>Stanford University</b><br>
  M.S. Computer Science (2019)<br>
  B.S. Biology (2016)"
  links :
    - label: 'DSullivan@mednet.ucla.edu'
      icon: "fas fa-fw fa-envelope-square"
      url: 'mailto:DSullivan@mednet.ucla.edu'
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: 'https://www.linkedin.com/in/delaney-sullivan-79989399'
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: 'https://scholar.google.com/citations?user=r8IhPSgAAAAJ'

footer:
  links :
    - label: 'DSullivan@mednet.ucla.edu'
      icon: "fas fa-fw fa-envelope-square"
      url: 'mailto:DSullivan@mednet.ucla.edu'
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: 'https://www.linkedin.com/in/delaney-sullivan-79989399'
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: 'https://scholar.google.com/citations?user=r8IhPSgAAAAJ'

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
